- id: docstring-coverage
  name: docstring-coverage
  description: Computes docstring coverage for Python code
  entry: docstring-coverage
  language: python
  args: ['--verbose', '0', '--hook-mode']
